# coding: utf-8

"""
    Unofficial python library for the SmartRecruiters API

    The SmartRecruiters API provides a platform to integrate services or applications, build apps and create fully customizable career sites. It exposes SmartRecruiters functionality and allows to connect and build software enhancing it.

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import smartrecruiters_python_client
from smartrecruiters_python_client.rest import ApiException
from smartrecruiters_python_client.apis.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """ MessagesApi unit test stubs """

    def setUp(self):
        self.api = smartrecruiters_python_client.apis.messages_api.MessagesApi()

    def tearDown(self):
        pass

    def test_messages_shares_create(self):
        """
        Test case for messages_shares_create

        Shares new messages on Hireloop with Users, Hiring Teams or Everyone and sends emails.
        """
        pass

    def test_messages_shares_delete(self):
        """
        Test case for messages_shares_delete

        Delete a message
        """
        pass


if __name__ == '__main__':
    unittest.main()
