# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import smartrecruiters_python_client
from smartrecruiters_python_client.rest import ApiException
from smartrecruiters_python_client.apis.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """ JobsApi unit test stubs """

    def setUp(self):
        self.api = smartrecruiters_python_client.apis.jobs_api.JobsApi()

    def tearDown(self):
        pass

    def test_jobs_all(self):
        """
        Test case for jobs_all

        Search jobs
        """
        pass

    def test_jobs_create(self):
        """
        Test case for jobs_create

        Create a new job
        """
        pass

    def test_jobs_get(self):
        """
        Test case for jobs_get

        Get content of a job with a given id.
        """
        pass

    def test_jobs_hiring_team_add(self):
        """
        Test case for jobs_hiring_team_add

        Add hiring team member of a job with a given id.
        """
        pass

    def test_jobs_hiring_team_get(self):
        """
        Test case for jobs_hiring_team_get

        Get hiring team of a job with a given id.
        """
        pass

    def test_jobs_hiring_team_remove(self):
        """
        Test case for jobs_hiring_team_remove

        Removes hiring team member of a job with a given id.
        """
        pass

    def test_jobs_jobads_all(self):
        """
        Test case for jobs_jobads_all

        Find and list job ads for a given job
        """
        pass

    def test_jobs_jobads_create(self):
        """
        Test case for jobs_jobads_create

        Create a new job ad
        """
        pass

    def test_jobs_jobads_get(self):
        """
        Test case for jobs_jobads_get

        Get a job ad
        """
        pass

    def test_jobs_jobads_postings_all(self):
        """
        Test case for jobs_jobads_postings_all

        List publications for a job ad
        """
        pass

    def test_jobs_jobads_postings_create(self):
        """
        Test case for jobs_jobads_postings_create

        Publishes a job ad
        """
        pass

    def test_jobs_jobads_postings_unpublish(self):
        """
        Test case for jobs_jobads_postings_unpublish

        Unpublish a job ad
        """
        pass

    def test_jobs_jobads_update(self):
        """
        Test case for jobs_jobads_update

        Update a job ad
        """
        pass

    def test_jobs_notes_get(self):
        """
        Test case for jobs_notes_get

        Get note of a job.
        """
        pass

    def test_jobs_notes_update(self):
        """
        Test case for jobs_notes_update

        Update note of a job.
        """
        pass

    def test_jobs_patch(self):
        """
        Test case for jobs_patch

        Update a job
        """
        pass

    def test_jobs_positions_all(self):
        """
        Test case for jobs_positions_all

        Positions for a job
        """
        pass

    def test_jobs_positions_create(self):
        """
        Test case for jobs_positions_create

        Create a new position for a job
        """
        pass

    def test_jobs_positions_get(self):
        """
        Test case for jobs_positions_get

        Get a single position
        """
        pass

    def test_jobs_positions_remove(self):
        """
        Test case for jobs_positions_remove

        Delete position
        """
        pass

    def test_jobs_positions_update(self):
        """
        Test case for jobs_positions_update

        Update position
        """
        pass

    def test_jobs_publication_all(self):
        """
        Test case for jobs_publication_all

        Find and list publications for a job
        """
        pass

    def test_jobs_publication_create(self):
        """
        Test case for jobs_publication_create

        Publishes a default job ad
        """
        pass

    def test_jobs_publication_unpublish(self):
        """
        Test case for jobs_publication_unpublish

        Unpublishes a job from all sources
        """
        pass

    def test_jobs_status_history_get(self):
        """
        Test case for jobs_status_history_get

        Job status history
        """
        pass

    def test_jobs_status_update(self):
        """
        Test case for jobs_status_update

        Updates job status
        """
        pass

    def test_jobs_update(self):
        """
        Test case for jobs_update

        Updates job
        """
        pass


if __name__ == '__main__':
    unittest.main()
