# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import smartrecruiters_python_client
from smartrecruiters_python_client.rest import ApiException
from smartrecruiters_python_client.apis.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """ AnalyticsApi unit test stubs """

    def setUp(self):
        self.api = smartrecruiters_python_client.apis.analytics_api.AnalyticsApi()

    def tearDown(self):
        pass

    def test_analytics_applications(self):
        """
        Test case for analytics_applications

        Get the list of applications.
        """
        pass

    def test_analytics_hiring_team(self):
        """
        Test case for analytics_hiring_team

        Get the list of hiring team members.
        """
        pass

    def test_analytics_interviews(self):
        """
        Test case for analytics_interviews

        Get the list of interviews.
        """
        pass

    def test_analytics_job_fields(self):
        """
        Test case for analytics_job_fields

        Get the list of job fields.
        """
        pass

    def test_analytics_jobs(self):
        """
        Test case for analytics_jobs

        Get the list of jobs.
        """
        pass

    def test_analytics_positions(self):
        """
        Test case for analytics_positions

        Get the list of job positions.
        """
        pass


if __name__ == '__main__':
    unittest.main()
