# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AnswerField(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, label=None, values=None):
        """
        AnswerField - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'label': 'str',
            'values': 'list[AnswerFieldValue]'
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'values': 'values'
        }

        self._id = id
        self._label = label
        self._values = values

    @property
    def id(self):
        """
        Gets the id of this AnswerField.

        :return: The id of this AnswerField.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AnswerField.

        :param id: The id of this AnswerField.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def label(self):
        """
        Gets the label of this AnswerField.
        Field label shown to candidate - ignore when empty

        :return: The label of this AnswerField.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this AnswerField.
        Field label shown to candidate - ignore when empty

        :param label: The label of this AnswerField.
        :type: str
        """

        self._label = label

    @property
    def values(self):
        """
        Gets the values of this AnswerField.
        Multiple values may be used for example for Multiselect Dropdown question

        :return: The values of this AnswerField.
        :rtype: list[AnswerFieldValue]
        """
        return self._values

    @values.setter
    def values(self, values):
        """
        Sets the values of this AnswerField.
        Multiple values may be used for example for Multiselect Dropdown question

        :param values: The values of this AnswerField.
        :type: list[AnswerFieldValue]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")

        self._values = values

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AnswerField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
