# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AssignmentJobActions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, details=None, position_details=None):
        """
        AssignmentJobActions - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'details': 'Action',
            'position_details': 'Action'
        }

        self.attribute_map = {
            'details': 'details',
            'position_details': 'positionDetails'
        }

        self._details = details
        self._position_details = position_details

    @property
    def details(self):
        """
        Gets the details of this AssignmentJobActions.

        :return: The details of this AssignmentJobActions.
        :rtype: Action
        """
        return self._details

    @details.setter
    def details(self, details):
        """
        Sets the details of this AssignmentJobActions.

        :param details: The details of this AssignmentJobActions.
        :type: Action
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")

        self._details = details

    @property
    def position_details(self):
        """
        Gets the position_details of this AssignmentJobActions.

        :return: The position_details of this AssignmentJobActions.
        :rtype: Action
        """
        return self._position_details

    @position_details.setter
    def position_details(self, position_details):
        """
        Sets the position_details of this AssignmentJobActions.

        :param position_details: The position_details of this AssignmentJobActions.
        :type: Action
        """

        self._position_details = position_details

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AssignmentJobActions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
