# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CandidateLocation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, country=None, country_code=None, region_code=None, region=None, city=None, lat=None, lng=None):
        """
        CandidateLocation - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'country': 'str',
            'country_code': 'str',
            'region_code': 'str',
            'region': 'str',
            'city': 'str',
            'lat': 'float',
            'lng': 'float'
        }

        self.attribute_map = {
            'country': 'country',
            'country_code': 'countryCode',
            'region_code': 'regionCode',
            'region': 'region',
            'city': 'city',
            'lat': 'lat',
            'lng': 'lng'
        }

        self._country = country
        self._country_code = country_code
        self._region_code = region_code
        self._region = region
        self._city = city
        self._lat = lat
        self._lng = lng

    @property
    def country(self):
        """
        Gets the country of this CandidateLocation.

        :return: The country of this CandidateLocation.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """
        Sets the country of this CandidateLocation.

        :param country: The country of this CandidateLocation.
        :type: str
        """
        if country is not None and len(country) < 1:
            raise ValueError("Invalid value for `country`, length must be greater than or equal to `1`")

        self._country = country

    @property
    def country_code(self):
        """
        Gets the country_code of this CandidateLocation.

        :return: The country_code of this CandidateLocation.
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """
        Sets the country_code of this CandidateLocation.

        :param country_code: The country_code of this CandidateLocation.
        :type: str
        """
        if country_code is not None and len(country_code) > 2:
            raise ValueError("Invalid value for `country_code`, length must be less than or equal to `2`")
        if country_code is not None and len(country_code) < 2:
            raise ValueError("Invalid value for `country_code`, length must be greater than or equal to `2`")

        self._country_code = country_code

    @property
    def region_code(self):
        """
        Gets the region_code of this CandidateLocation.

        :return: The region_code of this CandidateLocation.
        :rtype: str
        """
        return self._region_code

    @region_code.setter
    def region_code(self, region_code):
        """
        Sets the region_code of this CandidateLocation.

        :param region_code: The region_code of this CandidateLocation.
        :type: str
        """

        self._region_code = region_code

    @property
    def region(self):
        """
        Gets the region of this CandidateLocation.

        :return: The region of this CandidateLocation.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """
        Sets the region of this CandidateLocation.

        :param region: The region of this CandidateLocation.
        :type: str
        """

        self._region = region

    @property
    def city(self):
        """
        Gets the city of this CandidateLocation.

        :return: The city of this CandidateLocation.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this CandidateLocation.

        :param city: The city of this CandidateLocation.
        :type: str
        """
        if city is not None and len(city) < 1:
            raise ValueError("Invalid value for `city`, length must be greater than or equal to `1`")

        self._city = city

    @property
    def lat(self):
        """
        Gets the lat of this CandidateLocation.

        :return: The lat of this CandidateLocation.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """
        Sets the lat of this CandidateLocation.

        :param lat: The lat of this CandidateLocation.
        :type: float
        """

        self._lat = lat

    @property
    def lng(self):
        """
        Gets the lng of this CandidateLocation.

        :return: The lng of this CandidateLocation.
        :rtype: float
        """
        return self._lng

    @lng.setter
    def lng(self, lng):
        """
        Sets the lng of this CandidateLocation.

        :param lng: The lng of this CandidateLocation.
        :type: float
        """

        self._lng = lng

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CandidateLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
