# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CandidatePropertyFilter(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, values=None, actions=None):
        """
        CandidatePropertyFilter - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'values': 'CandidatePropertyFilterValues',
            'actions': 'Actions'
        }

        self.attribute_map = {
            'id': 'id',
            'values': 'values',
            'actions': 'actions'
        }

        self._id = id
        self._values = values
        self._actions = actions

    @property
    def id(self):
        """
        Gets the id of this CandidatePropertyFilter.

        :return: The id of this CandidatePropertyFilter.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CandidatePropertyFilter.

        :param id: The id of this CandidatePropertyFilter.
        :type: str
        """

        self._id = id

    @property
    def values(self):
        """
        Gets the values of this CandidatePropertyFilter.

        :return: The values of this CandidatePropertyFilter.
        :rtype: CandidatePropertyFilterValues
        """
        return self._values

    @values.setter
    def values(self, values):
        """
        Sets the values of this CandidatePropertyFilter.

        :param values: The values of this CandidatePropertyFilter.
        :type: CandidatePropertyFilterValues
        """

        self._values = values

    @property
    def actions(self):
        """
        Gets the actions of this CandidatePropertyFilter.

        :return: The actions of this CandidatePropertyFilter.
        :rtype: Actions
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """
        Sets the actions of this CandidatePropertyFilter.

        :param actions: The actions of this CandidatePropertyFilter.
        :type: Actions
        """

        self._actions = actions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CandidatePropertyFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
