# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CandidatePropertyDefinition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, label=None, type=None, availability=None, actions=None):
        """
        CandidatePropertyDefinition - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'label': 'str',
            'type': 'CandidatePropertyType',
            'availability': 'CandidatePropertyAvailability',
            'actions': 'Actions'
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'type': 'type',
            'availability': 'availability',
            'actions': 'actions'
        }

        self._id = id
        self._label = label
        self._type = type
        self._availability = availability
        self._actions = actions

    @property
    def id(self):
        """
        Gets the id of this CandidatePropertyDefinition.

        :return: The id of this CandidatePropertyDefinition.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CandidatePropertyDefinition.

        :param id: The id of this CandidatePropertyDefinition.
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """
        Gets the label of this CandidatePropertyDefinition.

        :return: The label of this CandidatePropertyDefinition.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this CandidatePropertyDefinition.

        :param label: The label of this CandidatePropertyDefinition.
        :type: str
        """

        self._label = label

    @property
    def type(self):
        """
        Gets the type of this CandidatePropertyDefinition.

        :return: The type of this CandidatePropertyDefinition.
        :rtype: CandidatePropertyType
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this CandidatePropertyDefinition.

        :param type: The type of this CandidatePropertyDefinition.
        :type: CandidatePropertyType
        """

        self._type = type

    @property
    def availability(self):
        """
        Gets the availability of this CandidatePropertyDefinition.

        :return: The availability of this CandidatePropertyDefinition.
        :rtype: CandidatePropertyAvailability
        """
        return self._availability

    @availability.setter
    def availability(self, availability):
        """
        Sets the availability of this CandidatePropertyDefinition.

        :param availability: The availability of this CandidatePropertyDefinition.
        :type: CandidatePropertyAvailability
        """

        self._availability = availability

    @property
    def actions(self):
        """
        Gets the actions of this CandidatePropertyDefinition.

        :return: The actions of this CandidatePropertyDefinition.
        :rtype: Actions
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """
        Sets the actions of this CandidatePropertyDefinition.

        :param actions: The actions of this CandidatePropertyDefinition.
        :type: Actions
        """

        self._actions = actions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CandidatePropertyDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
