# coding: utf-8

"""
    Unofficial python library for the SmartRecruiters API

    The SmartRecruiters API provides a platform to integrate services or applications, build apps and create fully customizable career sites. It exposes SmartRecruiters functionality and allows to connect and build software enhancing it.

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CandidateDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, internal=None, first_name=None, last_name=None, email=None, phone_number=None, location=None, web=None, created_on=None, updated_on=None, tags=None, average_rating=None, education=None, experience=None, primary_assignment=None, secondary_assignments=None, actions=None):
        """
        CandidateDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'internal': 'bool',
            'first_name': 'str',
            'last_name': 'str',
            'email': 'str',
            'phone_number': 'str',
            'location': 'CandidateLocation',
            'web': 'WebProfile',
            'created_on': 'datetime',
            'updated_on': 'datetime',
            'tags': 'list[str]',
            'average_rating': 'float',
            'education': 'list[Education]',
            'experience': 'list[Experience]',
            'primary_assignment': 'Assignment',
            'secondary_assignments': 'list[Assignment]',
            'actions': 'CandidateDetailsActions'
        }

        self.attribute_map = {
            'id': 'id',
            'internal': 'internal',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'phone_number': 'phoneNumber',
            'location': 'location',
            'web': 'web',
            'created_on': 'createdOn',
            'updated_on': 'updatedOn',
            'tags': 'tags',
            'average_rating': 'averageRating',
            'education': 'education',
            'experience': 'experience',
            'primary_assignment': 'primaryAssignment',
            'secondary_assignments': 'secondaryAssignments',
            'actions': 'actions'
        }

        self._id = id
        self._internal = internal
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._phone_number = phone_number
        self._location = location
        self._web = web
        self._created_on = created_on
        self._updated_on = updated_on
        self._tags = tags
        self._average_rating = average_rating
        self._education = education
        self._experience = experience
        self._primary_assignment = primary_assignment
        self._secondary_assignments = secondary_assignments
        self._actions = actions

    @property
    def id(self):
        """
        Gets the id of this CandidateDetails.

        :return: The id of this CandidateDetails.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CandidateDetails.

        :param id: The id of this CandidateDetails.
        :type: str
        """

        self._id = id

    @property
    def internal(self):
        """
        Gets the internal of this CandidateDetails.

        :return: The internal of this CandidateDetails.
        :rtype: bool
        """
        return self._internal

    @internal.setter
    def internal(self, internal):
        """
        Sets the internal of this CandidateDetails.

        :param internal: The internal of this CandidateDetails.
        :type: bool
        """

        self._internal = internal

    @property
    def first_name(self):
        """
        Gets the first_name of this CandidateDetails.

        :return: The first_name of this CandidateDetails.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this CandidateDetails.

        :param first_name: The first_name of this CandidateDetails.
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this CandidateDetails.

        :return: The last_name of this CandidateDetails.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this CandidateDetails.

        :param last_name: The last_name of this CandidateDetails.
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """
        Gets the email of this CandidateDetails.

        :return: The email of this CandidateDetails.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this CandidateDetails.

        :param email: The email of this CandidateDetails.
        :type: str
        """

        self._email = email

    @property
    def phone_number(self):
        """
        Gets the phone_number of this CandidateDetails.

        :return: The phone_number of this CandidateDetails.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """
        Sets the phone_number of this CandidateDetails.

        :param phone_number: The phone_number of this CandidateDetails.
        :type: str
        """

        self._phone_number = phone_number

    @property
    def location(self):
        """
        Gets the location of this CandidateDetails.

        :return: The location of this CandidateDetails.
        :rtype: CandidateLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this CandidateDetails.

        :param location: The location of this CandidateDetails.
        :type: CandidateLocation
        """

        self._location = location

    @property
    def web(self):
        """
        Gets the web of this CandidateDetails.

        :return: The web of this CandidateDetails.
        :rtype: WebProfile
        """
        return self._web

    @web.setter
    def web(self, web):
        """
        Sets the web of this CandidateDetails.

        :param web: The web of this CandidateDetails.
        :type: WebProfile
        """

        self._web = web

    @property
    def created_on(self):
        """
        Gets the created_on of this CandidateDetails.

        :return: The created_on of this CandidateDetails.
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """
        Sets the created_on of this CandidateDetails.

        :param created_on: The created_on of this CandidateDetails.
        :type: datetime
        """

        self._created_on = created_on

    @property
    def updated_on(self):
        """
        Gets the updated_on of this CandidateDetails.

        :return: The updated_on of this CandidateDetails.
        :rtype: datetime
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on):
        """
        Sets the updated_on of this CandidateDetails.

        :param updated_on: The updated_on of this CandidateDetails.
        :type: datetime
        """

        self._updated_on = updated_on

    @property
    def tags(self):
        """
        Gets the tags of this CandidateDetails.

        :return: The tags of this CandidateDetails.
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this CandidateDetails.

        :param tags: The tags of this CandidateDetails.
        :type: list[str]
        """

        self._tags = tags

    @property
    def average_rating(self):
        """
        Gets the average_rating of this CandidateDetails.

        :return: The average_rating of this CandidateDetails.
        :rtype: float
        """
        return self._average_rating

    @average_rating.setter
    def average_rating(self, average_rating):
        """
        Sets the average_rating of this CandidateDetails.

        :param average_rating: The average_rating of this CandidateDetails.
        :type: float
        """

        self._average_rating = average_rating

    @property
    def education(self):
        """
        Gets the education of this CandidateDetails.

        :return: The education of this CandidateDetails.
        :rtype: list[Education]
        """
        return self._education

    @education.setter
    def education(self, education):
        """
        Sets the education of this CandidateDetails.

        :param education: The education of this CandidateDetails.
        :type: list[Education]
        """

        self._education = education

    @property
    def experience(self):
        """
        Gets the experience of this CandidateDetails.

        :return: The experience of this CandidateDetails.
        :rtype: list[Experience]
        """
        return self._experience

    @experience.setter
    def experience(self, experience):
        """
        Sets the experience of this CandidateDetails.

        :param experience: The experience of this CandidateDetails.
        :type: list[Experience]
        """

        self._experience = experience

    @property
    def primary_assignment(self):
        """
        Gets the primary_assignment of this CandidateDetails.

        :return: The primary_assignment of this CandidateDetails.
        :rtype: Assignment
        """
        return self._primary_assignment

    @primary_assignment.setter
    def primary_assignment(self, primary_assignment):
        """
        Sets the primary_assignment of this CandidateDetails.

        :param primary_assignment: The primary_assignment of this CandidateDetails.
        :type: Assignment
        """

        self._primary_assignment = primary_assignment

    @property
    def secondary_assignments(self):
        """
        Gets the secondary_assignments of this CandidateDetails.

        :return: The secondary_assignments of this CandidateDetails.
        :rtype: list[Assignment]
        """
        return self._secondary_assignments

    @secondary_assignments.setter
    def secondary_assignments(self, secondary_assignments):
        """
        Sets the secondary_assignments of this CandidateDetails.

        :param secondary_assignments: The secondary_assignments of this CandidateDetails.
        :type: list[Assignment]
        """

        self._secondary_assignments = secondary_assignments

    @property
    def actions(self):
        """
        Gets the actions of this CandidateDetails.

        :return: The actions of this CandidateDetails.
        :rtype: CandidateDetailsActions
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """
        Sets the actions of this CandidateDetails.

        :param actions: The actions of this CandidateDetails.
        :type: CandidateDetailsActions
        """

        self._actions = actions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CandidateDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
