# coding: utf-8

"""
    Unofficial python library for the SmartRecruiters API

    The SmartRecruiters API provides a platform to integrate services or applications, build apps and create fully customizable career sites. It exposes SmartRecruiters functionality and allows to connect and build software enhancing it.

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class HiringProcess(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, active=None, sub_statuses=None):
        """
        HiringProcess - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'name': 'str',
            'active': 'bool',
            'sub_statuses': 'HiringProcessSubStatuses'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'active': 'active',
            'sub_statuses': 'subStatuses'
        }

        self._id = id
        self._name = name
        self._active = active
        self._sub_statuses = sub_statuses

    @property
    def id(self):
        """
        Gets the id of this HiringProcess.

        :return: The id of this HiringProcess.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this HiringProcess.

        :param id: The id of this HiringProcess.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this HiringProcess.

        :return: The name of this HiringProcess.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this HiringProcess.

        :param name: The name of this HiringProcess.
        :type: str
        """

        self._name = name

    @property
    def active(self):
        """
        Gets the active of this HiringProcess.

        :return: The active of this HiringProcess.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this HiringProcess.

        :param active: The active of this HiringProcess.
        :type: bool
        """

        self._active = active

    @property
    def sub_statuses(self):
        """
        Gets the sub_statuses of this HiringProcess.

        :return: The sub_statuses of this HiringProcess.
        :rtype: HiringProcessSubStatuses
        """
        return self._sub_statuses

    @sub_statuses.setter
    def sub_statuses(self, sub_statuses):
        """
        Sets the sub_statuses of this HiringProcess.

        :param sub_statuses: The sub_statuses of this HiringProcess.
        :type: HiringProcessSubStatuses
        """

        self._sub_statuses = sub_statuses

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, HiringProcess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
