# coding: utf-8

"""
    Unofficial python library for the SmartRecruiters API

    The SmartRecruiters API provides a platform to integrate services or applications, build apps and create fully customizable career sites. It exposes SmartRecruiters functionality and allows to connect and build software enhancing it.

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Job(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, title=None, ref_number=None, created_on=None, updated_on=None, last_activity_on=None, department=None, location=None, status=None, posting_status=None):
        """
        Job - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'title': 'str',
            'ref_number': 'str',
            'created_on': 'datetime',
            'updated_on': 'datetime',
            'last_activity_on': 'datetime',
            'department': 'Department',
            'location': 'Location',
            'status': 'JobStatus',
            'posting_status': 'PostingStatus'
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'ref_number': 'refNumber',
            'created_on': 'createdOn',
            'updated_on': 'updatedOn',
            'last_activity_on': 'lastActivityOn',
            'department': 'department',
            'location': 'location',
            'status': 'status',
            'posting_status': 'postingStatus'
        }

        self._id = id
        self._title = title
        self._ref_number = ref_number
        self._created_on = created_on
        self._updated_on = updated_on
        self._last_activity_on = last_activity_on
        self._department = department
        self._location = location
        self._status = status
        self._posting_status = posting_status

    @property
    def id(self):
        """
        Gets the id of this Job.

        :return: The id of this Job.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Job.

        :param id: The id of this Job.
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """
        Gets the title of this Job.

        :return: The title of this Job.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this Job.

        :param title: The title of this Job.
        :type: str
        """

        self._title = title

    @property
    def ref_number(self):
        """
        Gets the ref_number of this Job.

        :return: The ref_number of this Job.
        :rtype: str
        """
        return self._ref_number

    @ref_number.setter
    def ref_number(self, ref_number):
        """
        Sets the ref_number of this Job.

        :param ref_number: The ref_number of this Job.
        :type: str
        """

        self._ref_number = ref_number

    @property
    def created_on(self):
        """
        Gets the created_on of this Job.

        :return: The created_on of this Job.
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """
        Sets the created_on of this Job.

        :param created_on: The created_on of this Job.
        :type: datetime
        """

        self._created_on = created_on

    @property
    def updated_on(self):
        """
        Gets the updated_on of this Job.
        Job modification date

        :return: The updated_on of this Job.
        :rtype: datetime
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on):
        """
        Sets the updated_on of this Job.
        Job modification date

        :param updated_on: The updated_on of this Job.
        :type: datetime
        """

        self._updated_on = updated_on

    @property
    def last_activity_on(self):
        """
        Gets the last_activity_on of this Job.
        Indicates last activity associated with a job

        :return: The last_activity_on of this Job.
        :rtype: datetime
        """
        return self._last_activity_on

    @last_activity_on.setter
    def last_activity_on(self, last_activity_on):
        """
        Sets the last_activity_on of this Job.
        Indicates last activity associated with a job

        :param last_activity_on: The last_activity_on of this Job.
        :type: datetime
        """

        self._last_activity_on = last_activity_on

    @property
    def department(self):
        """
        Gets the department of this Job.

        :return: The department of this Job.
        :rtype: Department
        """
        return self._department

    @department.setter
    def department(self, department):
        """
        Sets the department of this Job.

        :param department: The department of this Job.
        :type: Department
        """

        self._department = department

    @property
    def location(self):
        """
        Gets the location of this Job.

        :return: The location of this Job.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this Job.

        :param location: The location of this Job.
        :type: Location
        """

        self._location = location

    @property
    def status(self):
        """
        Gets the status of this Job.

        :return: The status of this Job.
        :rtype: JobStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this Job.

        :param status: The status of this Job.
        :type: JobStatus
        """

        self._status = status

    @property
    def posting_status(self):
        """
        Gets the posting_status of this Job.

        :return: The posting_status of this Job.
        :rtype: PostingStatus
        """
        return self._posting_status

    @posting_status.setter
    def posting_status(self, posting_status):
        """
        Sets the posting_status of this Job.

        :param posting_status: The posting_status of this Job.
        :type: PostingStatus
        """

        self._posting_status = posting_status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Job):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
