# coding: utf-8

"""
    Unofficial python library for the SmartRecruiters API

    The SmartRecruiters API provides a platform to integrate services or applications, build apps and create fully customizable career sites. It exposes SmartRecruiters functionality and allows to connect and build software enhancing it.

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OfferActions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, candidate=None, job=None, details=None):
        """
        OfferActions - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'candidate': 'Action',
            'job': 'Action',
            'details': 'Action'
        }

        self.attribute_map = {
            'candidate': 'candidate',
            'job': 'job',
            'details': 'details'
        }

        self._candidate = candidate
        self._job = job
        self._details = details

    @property
    def candidate(self):
        """
        Gets the candidate of this OfferActions.

        :return: The candidate of this OfferActions.
        :rtype: Action
        """
        return self._candidate

    @candidate.setter
    def candidate(self, candidate):
        """
        Sets the candidate of this OfferActions.

        :param candidate: The candidate of this OfferActions.
        :type: Action
        """
        if candidate is None:
            raise ValueError("Invalid value for `candidate`, must not be `None`")

        self._candidate = candidate

    @property
    def job(self):
        """
        Gets the job of this OfferActions.

        :return: The job of this OfferActions.
        :rtype: Action
        """
        return self._job

    @job.setter
    def job(self, job):
        """
        Sets the job of this OfferActions.

        :param job: The job of this OfferActions.
        :type: Action
        """

        self._job = job

    @property
    def details(self):
        """
        Gets the details of this OfferActions.

        :return: The details of this OfferActions.
        :rtype: Action
        """
        return self._details

    @details.setter
    def details(self, details):
        """
        Sets the details of this OfferActions.

        :param details: The details of this OfferActions.
        :type: Action
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")

        self._details = details

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OfferActions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
