# coding: utf-8

"""
    Customer API - version 1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserListItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, email=None, first_name=None, last_name=None, role=None, external_data=None, language=None, id=None, active=None, updated_on=None):
        """
        UserListItem - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'email': 'str',
            'first_name': 'str',
            'last_name': 'str',
            'role': 'str',
            'external_data': 'str',
            'language': 'UserLanguage',
            'id': 'str',
            'active': 'bool',
            'updated_on': 'datetime'
        }

        self.attribute_map = {
            'email': 'email',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'role': 'role',
            'external_data': 'externalData',
            'language': 'language',
            'id': 'id',
            'active': 'active',
            'updated_on': 'updatedOn'
        }

        self._email = email
        self._first_name = first_name
        self._last_name = last_name
        self._role = role
        self._external_data = external_data
        self._language = language
        self._id = id
        self._active = active
        self._updated_on = updated_on

    @property
    def email(self):
        """
        Gets the email of this UserListItem.

        :return: The email of this UserListItem.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this UserListItem.

        :param email: The email of this UserListItem.
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this UserListItem.

        :return: The first_name of this UserListItem.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this UserListItem.

        :param first_name: The first_name of this UserListItem.
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")
        if first_name is not None and len(first_name) > 300:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `300`")
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this UserListItem.

        :return: The last_name of this UserListItem.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this UserListItem.

        :param last_name: The last_name of this UserListItem.
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")
        if last_name is not None and len(last_name) > 300:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `300`")
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")

        self._last_name = last_name

    @property
    def role(self):
        """
        Gets the role of this UserListItem.

        :return: The role of this UserListItem.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """
        Sets the role of this UserListItem.

        :param role: The role of this UserListItem.
        :type: str
        """
        allowed_values = ["EMPLOYEE", "RESTRICTED", "STANDARD", "EXTENDED", "ADMINISTRATOR"]
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def external_data(self):
        """
        Gets the external_data of this UserListItem.

        :return: The external_data of this UserListItem.
        :rtype: str
        """
        return self._external_data

    @external_data.setter
    def external_data(self, external_data):
        """
        Sets the external_data of this UserListItem.

        :param external_data: The external_data of this UserListItem.
        :type: str
        """

        self._external_data = external_data

    @property
    def language(self):
        """
        Gets the language of this UserListItem.

        :return: The language of this UserListItem.
        :rtype: UserLanguage
        """
        return self._language

    @language.setter
    def language(self, language):
        """
        Sets the language of this UserListItem.

        :param language: The language of this UserListItem.
        :type: UserLanguage
        """

        self._language = language

    @property
    def id(self):
        """
        Gets the id of this UserListItem.

        :return: The id of this UserListItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this UserListItem.

        :param id: The id of this UserListItem.
        :type: str
        """

        self._id = id

    @property
    def active(self):
        """
        Gets the active of this UserListItem.

        :return: The active of this UserListItem.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this UserListItem.

        :param active: The active of this UserListItem.
        :type: bool
        """

        self._active = active

    @property
    def updated_on(self):
        """
        Gets the updated_on of this UserListItem.

        :return: The updated_on of this UserListItem.
        :rtype: datetime
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on):
        """
        Sets the updated_on of this UserListItem.

        :param updated_on: The updated_on of this UserListItem.
        :type: datetime
        """

        self._updated_on = updated_on

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserListItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
